config/routes.rb
Rails.application.routes.draw do
  # post '/callback' => 'scores#callback'
  post '/callback' => 'line_bot#callback'

  resources :scores, only: [:index, :edit, :update]
  root to: "scores#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < Inum::Base
  define :FRANCE, 0
  define :GERMANY, 1
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :score

  bind_inum :winner, Country, _prefix: true
  bind_inum :loser,  Country, _prefix: true

  with_options presence: true do
    validates :winner
    validates :loser
    validates :score_id
  end
end

app/models/score.rb
class Score < ApplicationRecord
  has_one :result
  with_options presence: true do
    validates :france
    validates :germany
    validates :france_pk
    validates :germany_pk
  end
  
  with_options numericality: { only_integer: true } do
    validates :france
    validates :germany
    validates :france_pk
    validates :germany_pk
  end

  def self.total_wins
    return '🇫🇷勝ち数🇩🇪' + "\n" + Score.where("france + france_pk > germany + germany_pk").count.to_s + '勝' + " - " + Score.where("france + france_pk < germany + germany_pk").count.to_s + '勝' + "\n" + "\n"
  end

  def self.scoring_rate
    return '🇫🇷得点率🇩🇪' + "\n" + "#{Score.average(:france).round(1).to_s}点" + ' - ' + "#{Score.average(:germany).round(1).to_s}点" + "\n" + "\n"
  end

  def self.total_scores
    total_france_score = Score.sum(:france)
    total_germany = Score.sum(:germany)
    return '🇫🇷総得点🇩🇪' + "\n" + "#{total_france_score.to_s}点" + ' - ' + "#{total_germany.to_s}点" + "\n" + "\n"
  end

  def self.total_matches
    return '🇫🇷総試合数🇩🇪' + "\n" +  Score.count.to_s + '試合' + "\n" + "\n"
  end

  def self.is_next_match?
    next_matche = Score.count + 1
    (next_matche % 10 == 0) ? "次は記念すべき#{next_matche}試合目やでぇ！！" : "次はどっちが勝つかな？"
  end

  def self.match_result(scores, text)
    text << (scores.length == 1 ? '🇫🇷得点🇩🇪' : '🇫🇷直近５試合の結果🇩🇪')
    text << "\n"
    scores.each do |score|
      text << score[:france].to_s + ' ' + '-' + ' ' + score[:germany].to_s
      text << '（' + ' ' + score[:france_pk].to_s + ' ' + '-' + ' ' + score[:germany_pk].to_s + ' ' + '）' unless (score[:france_pk] == 0 && score[:germany_pk] == 0)
      text << "\n"
    end
    text << "\n"
  end

  def self.save_from_message(scores)
    # pk戦じゃなければ0を代入する
    if scores.length == 2
      pk_flanse_score = 0
      germany_pk = 0
    end

    if scores.length == 4
      pk_flanse_score = scores[2]
      germany_pk = scores[3]
    end

    raise ArgumentError, "#{scores} is invalid length" unless scores.length == 2 || scores.length == 4

    winner = (scores[0] + pk_flanse_score > scores[1] + germany_pk) ? "FRANCE" : "GERMANY"
    loser = (winner == "FRANCE") ? "GERMANY" : "FRANCE"
    score = Score.new(france: scores[0], germany: scores[1], france_pk: pk_flanse_score, germany_pk: germany_pk)
    result = score.build_result(winner: Object.const_get("Country::#{winner}"), loser: Object.const_get("Country::#{loser}"))

    raise ArgumentError, "#{scores} is invalid values" if score.invalid? || (scores[0] + pk_flanse_score) == (scores[1] + germany_pk)

    score.save!
  end

  def self.results
    text = ''
    text << Score.total_matches
    scores = Score.all.order(id: 'DESC').limit(5)
    Score.match_result(scores, text)

    text << Score.total_wins
    text << Score.scoring_rate
    text << Score.total_scores
    text << Score.is_next_match?
  end
end

app/models/wininng.rb
class Wininng < ApplicationRecord
  validates :count,   numericality: { only_integer: true }, presence: true
  validates :country, uniqueness: true
  
  with_options presence: true do
    validates :count
    validates :country
  end

  bind_inum :country, Country

  def self.update_count_of_winner_and_loser!(winner, loser)
    wininng_record_of_winner = Wininng.find_or_create_by(country: winner)
    loser_record_of_winner = Wininng.find_or_create_by(country: loser)

    wininng_record_of_winner.update!(count: wininng_record_of_winner[:count] += 1)
    loser_record_of_winner.update!(count: 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/line_bot_controller.rb
require 'line/bot'


# webhook_URL : https://score-log-bot.herokuapp.com/callback

class LineBotController < ApplicationController
  protect_from_forgery except: [:callback]

  def callback
    body = request.body.read
    signature = request.env['HTTP_X_LINE_SIGNATURE']
    unless client.validate_signature(body, signature)
      error 400 do 'Bad Request' end
    end
  
    events = client.parse_events_from(body)
    events.each do |event|
      case event
      when Line::Bot::Event::Message
        case event.type
        when Line::Bot::Event::MessageType::Text
          text = event.message['text']
          scores = event.message['text'].split(" ").map!(&:to_i)

          scores.slice!(2, 2) if (scores.length == 4) && (scores[2] == 0) && (scores[3] == 0)

          response_message = if is_result(text)
                               Score.results
                             elsif valid_score_check(scores)
                               reply = ReplyService.new(scores)
                               reply.call!
                             else
                               'none'
                             end

          return if response_message == 'none'

          message = {
            type: 'text',
            text: response_message
          }
          client.reply_message(event['replyToken'], message)

        when Line::Bot::Event::MessageType::Image, Line::Bot::Event::MessageType::Video
          response = client.get_message_content(event.message['id'])
          tf = Tempfile.open("content")
          tf.write(response.body)
        end
      end
    end
  
    # Don't forget to return a successful response
    head :ok
  end

  private
  def client
    @client ||= Line::Bot::Client.new { |config|
      config.channel_id = ENV["LINE_CHANNEL_ID"]
      config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
      config.channel_token = ENV["LINE_CHANNEL_TOKEN"]
    }
  end

  def valid_score_check(scores)
    return false unless scores.instance_of?(Array) && (scores.length == 4 || scores.length == 2)
    scores.length == 2 ? (scores[0] != scores[1]) : (scores[0] == scores[1] && scores[2] != scores[3])
  end

  def is_result(text)
    return text == '結果'
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :find_score, only: [:edit, :update]
  def index
    @scores = Score.all.order(id: :desc)
  end

  def edit
    basic_auth
    @score = Score.find(params[:id])
  end

  def update
    if @score.update(score_params)
      redirect_to root_path, notice: '修正完了！'
    else
      flash.now[:alert] = "スコアは半角数字で入力してください。"
      render :edit
    end
  end

  private

  def find_score
    @score = Score.find(params[:id])
  end

  def score_params
    params.require(:score).permit(:france, :germany, :france_pk, :germany_pk)
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["SCORE_USER"] && password == ENV["SCORE_PASSWORD"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_bot_helper.rb
module LineBotHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoreLogBot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href = "https://unpkg.com/sanitize.css" rel = " stylesheet " type="text/css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=“container”>
    <nav class="navbar navbar-dark bg-info">
      <div class="container-fluid">
        <%= link_to "ScoreLogBot", root_path , class:"navbar-brand" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/scores/edit.html.erb
<% if flash.now[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash.now[:alert] %></div>
<% end %>
<h3 class="mt-5 mb-5">スコアを編集する</h1>

<%= form_with model:@score, local: true do |f|%>
<table class="table">
  <thead>
    <tr>

      <th scope="col">得点</th>
      <th scope="col">PK</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>

      <td class="align-middle"><%= f.text_field :france, class:"form", autofocus: true %> - <%= f.text_field :germany, class:"form"%></td>
      <td class="align-middle"><%= f.text_field :france_pk, class:"form" %> - <%= f.text_field :germany_pk, class:"form"%></td>
      <td class="align-middle"><%= f.submit "決定", class:"btn btn-outline-success me-2 btn-lg"%></td>
    </tr>
  </tbody>
</table>
<%end%>

app/views/scores/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">日付</th>
      <th scope="col">得点</th>
      <th scope="col">PK</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

  <% @scores.each do |score|%>
    <tr>
      <th scope="row" class="align-middle"><%=l score[:created_at] %></th>
      <td class="align-middle"><%= score[:france] %> - <%= score[:germany] %></td>
      <td class="align-middle"><%= score[:france_pk] %> - <%= score[:germany_pk] %></td>
      <td class="align-middle"><%= link_to "修正", edit_score_path(score[:id]) , class:"btn btn-outline-success me-2 btn-lg"%></td>
    </tr>
  <%end%>
  </tbody>
</table>